services:


  #jupyter
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"  # Porta padrão da interface web do Jupyter Notebook
        #      - "4040:4040"  # Porta padrão da interface web do Spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
      - ./config:/home/jovyan/.jupyter
    networks:
      - mybridge

  #mongodb
  mongo:
    image: mongo:4.4-bionic
    container_name: mongo_service
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
      - ./db-seed:/db-seed
      - ./datasets:/datasets
    networks:
      - mybridge

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_service
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:mongo@mongo_service:27017/?authSource=admin
    ports:
      - "8081:8081"
    networks:
      - mybridge
    depends_on:
      - mongo
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh


  #cassandra
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    networks:
      - mybridge
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./datasets:/datasets

# Configuração das redes que serão usadas no docker-compose.
networks:
  mybridge: # Nome da rede.
    external: true # Indica que a rede é externa e já foi criada anteriormente.
    name: mybridge # Nome da rede externa que será usada.

volumes:
  mongo_data:
  cassandra_data:
  notebooks:
  data:
  config:
  dbdata:
  db-seed:
